baseURL = 'https://rgp-site.pages.dev'
languageCode = 'en-us'
title = 'The Rio Grande Plan'

defaultContentLanguage = "en"
sectionPagesMenu = "main"

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'