baseURL = 'https://rgp-site.pages.dev'
languageCode = 'en-us'
title = 'The Rio Grande Plan'

defaultContentLanguage = "en"
sectionPagesMenu = "main"

# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true

[cascade]
featured_image = '/images/ground_render.jpg'

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'