[[main]]
    name = "Comercio"
    url = "https://store.viariogrande.org/"
    weight = 998
    params = { external = true }

[[main]]
    name = "Donar"
    url = "https://store.viariogrande.org/product/donation/"
    weight = 999
    params = { external = true }
