[[main]]
    name = "Shop"
    url = "https://store.viariogrande.org/"
    weight = 998
    params = { external = true }

[[main]]
    name = "Donate"
    url = "https://store.viariogrande.org/product/donation/"
    weight = 999
    params = { external = true }
