# The URL the site will be built for
base_url = "https://rgp-site.pages.dev"
title = "The Rio Grande Plan"
description = "A Citizen Proposal to Restore Rail Service to the Rio Grande Depot and reconnect our divided community."
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# theme = "daisy"

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
nav_links = [
    { name = "About", url = "$BASE_URL/about/" },
    { name = "Reports", url = "$BASE_URL/reports/" },
    { name = "Get Involved", url = "$BASE_URL/get-involved/" }
]

[extra.social]
instagram = "https://www.instagram.com/riograndeplan"
linkedin = "https://www.linkedin.com/company/via-rio-grande"
youtube = "https://www.youtube.com/@CSLenhart"